spring.application.name=gateway-service
server.port=8080

# ? FIXES crash
eureka.client.enabled=false
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
spring.cloud.discovery.enabled=false
spring.cloud.gateway.discovery.locator.enabled=false  # ? ADD THIS TOO

# ROUTING
# AUTH SERVICE ROUTE
spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/auth/**

# USER SERVICE ROUTE
spring.cloud.gateway.server.webflux.routes[1].id=user-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/user/**,/api/admin/**

# DOCUMENT SERVICE ROUTE
spring.cloud.gateway.server.webflux.routes[2].id=document-service
spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:8083
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/documents/**

# JWT PUBLIC KEY LOCATION
spring.security.oauth2.resourceserver.jwt.public-key-location=classpath:keys/public.pem