spring.application.name=collaboration-service
server.port=8085

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.security.oauth2.resourceserver.jwt.public-key-location=classpath:keys/public.pem