
spring.application.name=team-service
server.port=8084

spring.datasource.url=jdbc:postgresql://localhost:5432/teamdb
spring.datasource.username=postgres
spring.datasource.password=sqlpro

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.security.oauth2.resourceserver.jwt.public-key-location=classpath:keys/public.pem