spring.application.name=auth-service

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/auth_db
spring.datasource.username=postgres
spring.datasource.password=sqlpro

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ================= JWT (RS256) =================
jwt.private-key=keys/private.pem
jwt.public-key=keys/public.pem

jwt.access.expiration=900000
jwt.refresh.expiration=604800000

google.client.id=769453934960-76o89h3pd85e3kbk2fbie898s5sna7og.apps.googleusercontent.com

